GMAIL_DOMAIN: 'labthi.ng'
GMAIL_USERNAME: 'labthingco'
GMAIL_PASSWORD: 'amavfsimperi4l'

S3_BUCKET_NAME: 'labthi.ng'
S3_KEY: 'AKIAI2GFGIII6MDPRG6Q'
S3_SECRET: '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'

LABTHING_DATABASE_PASSWORD: 'Gq9DIfPCBS'
