require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IdeaTagsController do

  # This should return the minimal set of attributes required to create a valid
  # IdeaTag. As you add validations to IdeaTag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IdeaTagsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all idea_tags as @idea_tags" do
      idea_tag = IdeaTag.create! valid_attributes
      get :index, {}, valid_session
      assigns(:idea_tags).should eq([idea_tag])
    end
  end

  describe "GET show" do
    it "assigns the requested idea_tag as @idea_tag" do
      idea_tag = IdeaTag.create! valid_attributes
      get :show, {:id => idea_tag.to_param}, valid_session
      assigns(:idea_tag).should eq(idea_tag)
    end
  end

  describe "GET new" do
    it "assigns a new idea_tag as @idea_tag" do
      get :new, {}, valid_session
      assigns(:idea_tag).should be_a_new(IdeaTag)
    end
  end

  describe "GET edit" do
    it "assigns the requested idea_tag as @idea_tag" do
      idea_tag = IdeaTag.create! valid_attributes
      get :edit, {:id => idea_tag.to_param}, valid_session
      assigns(:idea_tag).should eq(idea_tag)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IdeaTag" do
        expect {
          post :create, {:idea_tag => valid_attributes}, valid_session
        }.to change(IdeaTag, :count).by(1)
      end

      it "assigns a newly created idea_tag as @idea_tag" do
        post :create, {:idea_tag => valid_attributes}, valid_session
        assigns(:idea_tag).should be_a(IdeaTag)
        assigns(:idea_tag).should be_persisted
      end

      it "redirects to the created idea_tag" do
        post :create, {:idea_tag => valid_attributes}, valid_session
        response.should redirect_to(IdeaTag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved idea_tag as @idea_tag" do
        # Trigger the behavior that occurs when invalid params are submitted
        IdeaTag.any_instance.stub(:save).and_return(false)
        post :create, {:idea_tag => { "name" => "invalid value" }}, valid_session
        assigns(:idea_tag).should be_a_new(IdeaTag)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IdeaTag.any_instance.stub(:save).and_return(false)
        post :create, {:idea_tag => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested idea_tag" do
        idea_tag = IdeaTag.create! valid_attributes
        # Assuming there are no other idea_tags in the database, this
        # specifies that the IdeaTag created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IdeaTag.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => idea_tag.to_param, :idea_tag => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested idea_tag as @idea_tag" do
        idea_tag = IdeaTag.create! valid_attributes
        put :update, {:id => idea_tag.to_param, :idea_tag => valid_attributes}, valid_session
        assigns(:idea_tag).should eq(idea_tag)
      end

      it "redirects to the idea_tag" do
        idea_tag = IdeaTag.create! valid_attributes
        put :update, {:id => idea_tag.to_param, :idea_tag => valid_attributes}, valid_session
        response.should redirect_to(idea_tag)
      end
    end

    describe "with invalid params" do
      it "assigns the idea_tag as @idea_tag" do
        idea_tag = IdeaTag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IdeaTag.any_instance.stub(:save).and_return(false)
        put :update, {:id => idea_tag.to_param, :idea_tag => { "name" => "invalid value" }}, valid_session
        assigns(:idea_tag).should eq(idea_tag)
      end

      it "re-renders the 'edit' template" do
        idea_tag = IdeaTag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IdeaTag.any_instance.stub(:save).and_return(false)
        put :update, {:id => idea_tag.to_param, :idea_tag => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested idea_tag" do
      idea_tag = IdeaTag.create! valid_attributes
      expect {
        delete :destroy, {:id => idea_tag.to_param}, valid_session
      }.to change(IdeaTag, :count).by(-1)
    end

    it "redirects to the idea_tags list" do
      idea_tag = IdeaTag.create! valid_attributes
      delete :destroy, {:id => idea_tag.to_param}, valid_session
      response.should redirect_to(idea_tags_url)
    end
  end

end
